version: '3'
services:
  # https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose
  #PHP Service
  app:
    image: laravel-fpm
    links:
      - db:mysql
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: app
      REDIS_PORT: 6379
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - app_code:/var/www/html/
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./storage/app:/var/www/html/storage/app
    networks:
      - backend

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: abc-webserver
    restart: unless-stopped
    volumes:
      - app_code:/var/www/html/
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      VIRTUAL_HOST: lms.abc-chinaedu.com,lms.daxiangyingyu.com
      LETSENCRYPT_HOST: lms.abc-chinaedu.com,lms.daxiangyingyu.com
      LETSENCRYPT_EMAIL: dale.tel@139.com
    networks:
      - overlay
      - backend
    links:
      - app

  #MySQL Service
  db:
    image: mysql:latest
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - /tmp:/sql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    networks:
      - backend

  scheduler:
    image: laravel-fpm
    restart: always
    depends_on:
      - app
    links:
      - db:mysql
      - redis
    networks:
      - backend
    volumes:
      - ./storage/app:/var/www/html/storage/app
    environment:
      REDIS_PORT: 6379
      CONTAINER_ROLE: scheduler
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
  queue:
    image: laravel-fpm
    restart: always
    depends_on:
      - app
    links:
      - db:mysql
      - redis
    networks:
      - backend
    volumes:
      - ./storage/app:/var/www/html/storage/app
    environment:
      REDIS_PORT: 6379
      CONTAINER_ROLE: queue
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
#Docker Networks
networks:
  overlay:
    driver: bridge
  backend:
volumes:
  db_data:
  app_code:
